/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftTest.h"
#include "async/TAsyncChannel.h"
#include "ThriftTest.tcc"

namespace thrift { namespace test {

}} // namespace

